name: CI/CD Pipelines

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar script de build
        run: echo "Hello, world! — Build executado"

  deploy-dev:
    name: Deploy DEV
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev
      url: https://josenilto.github.io/dev

    steps:
      - name: Executar deploy DEV
        run: echo "Deploy DEV executado"

  deploy-hmg:
    name: Deploy HMG
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: hmg
      url: https://josenilto.github.io/hmg

    steps:
      - name: Executar deploy HMG
        run: echo "Deploy HMG executado"

  deploy-prd:
    name: Deploy PRD
    runs-on: ubuntu-latest
    needs: deploy-hmg
    environment:
      name: prd
      url: https://josenilto.github.io/

    steps:
      - name: Executar deploy PRD
        run: echo "Deploy PRD executado"
